import { StyleResolver } from '../core/StyleResolver';
import { TFolder } from 'obsidian';
import { IColorfulFoldersPlugin } from '../common/types';

/** Converts a hex color string to the integer RGB format Obsidian's graph.json expects. */
function hexToGraphRgb(hex: string): number {
    const clean = hex.replace('#', '');
    const r = parseInt(clean.substring(0, 2), 16);
    const g = parseInt(clean.substring(2, 4), 16);
    const b = parseInt(clean.substring(4, 6), 16);
    return (r << 16) | (g << 8) | b;
}

/**
 * Escapes a folder path/name for use in an Obsidian graph query.
 * Wraps in quotes to handle spaces and special characters.
 * NOTE: The `+` folder name is a special case — we skip it because
 * Obsidian treats `+` as a boolean operator in its search engine,
 * making it impossible to use as a path query token.
 */
function isSafeQueryPath(name: string): boolean {
    // Skip folders whose names are pure Obsidian search operators
    // or single special characters that would break query parsing.
    const unsafe = /^[+\-!(){}[\]^"~*?:\\/]$/.test(name.trim());
    return !unsafe && name.trim().length > 0;
}

interface GraphColorGroup {
    query: string;
    color: { a: number; rgb: number };
}

interface GraphJson {
    colorGroups?: GraphColorGroup[];
    /** Tracks which colorGroup queries were generated by CF so we can cleanly replace them. */
    'cf-managed-queries'?: string[];
    [key: string]: unknown;
}

/**
 * GraphColorSync Integration
 *
 * Syncs Colorful Folders' per-folder colors into Obsidian's native Graph View
 * by writing path-based colorGroups to .obsidian/graph.json.
 *
 * Strategy:
 * - Syncs all top-level folders + any folder with an explicit custom color.
 * - CF-owned groups are tracked via a separate `cf-managed-queries` array in
 *   graph.json. This avoids polluting the actual query strings with tags that
 *   would break Obsidian's graph search engine.
 * - User-created groups are NEVER modified or deleted — they are preserved
 *   at the front of the colorGroups array (higher priority in the graph renderer).
 */
export class GraphColorSync {

    /**
     * Builds the array of CF-owned colorGroups from the current plugin state.
     * Walks all top-level folders and any folder with an explicit custom style.
     */
    static buildColorGroups(plugin: IColorfulFoldersPlugin): GraphColorGroup[] {
        const groups: GraphColorGroup[] = [];
        const seen = new Set<string>();
        const root = plugin.app.vault.getRoot();

        const processFolder = (folder: TFolder) => {
            if (seen.has(folder.path)) return;
            seen.add(folder.path);

            if (folder.path === '/' || folder.isRoot()) {
                const rootStyle = plugin.settings.customFolderColors['/'] || plugin.settings.customFolderColors[''];
                const hex = typeof rootStyle === 'string' ? rootStyle : rootStyle?.hex;
                if (hex && hex.length >= 4 && !hex.startsWith('var(')) {
                    groups.push({
                        query: 'path:"/"',
                        color: { a: 1, rgb: hexToGraphRgb(hex) }
                    });
                }
                for (const child of folder.children) {
                    if (child.name.startsWith('.')) continue;
                    if (child instanceof TFolder) processFolder(child);
                }
                return;
            }

            if (!isSafeQueryPath(folder.name)) {
                // Still walk children in case they have explicit custom styles
                for (const child of folder.children) {
                    if (child.name.startsWith('.')) continue;
                    if (child instanceof TFolder) {
                        if (plugin.settings.customFolderColors[child.path]) {
                            processFolder(child);
                        }
                    }
                }
                return;
            }

            const style = StyleResolver.getEffectiveStyle(folder, plugin);
            const hex = style?.hex;
            if (!hex || hex.length < 4 || hex.startsWith('var(')) {
                // No valid hex — still walk children for explicitly styled subfolders
                for (const child of folder.children) {
                    if (child.name.startsWith('.')) continue;
                    if (child instanceof TFolder && plugin.settings.customFolderColors[child.path]) {
                        processFolder(child);
                    }
                }
                return;
            }

            // Build the query. Use folder path for nested folders, just name for top-level.
            const isTopLevel = !folder.parent || folder.parent.isRoot() || folder.parent.path === '/' || folder.parent.path === '';
            const queryTarget = isTopLevel ? folder.name : folder.path;
            const query = `path:"${queryTarget}"`;

            groups.push({
                query,
                color: { a: 1, rgb: hexToGraphRgb(hex) }
            });

            // Recurse into children that have explicit custom styles
            for (const child of folder.children) {
                if (child.name.startsWith('.')) continue;
                if (child instanceof TFolder && plugin.settings.customFolderColors[child.path]) {
                    processFolder(child);
                }
            }
        };

        for (const child of root.children) {
            if (child.name.startsWith('.')) continue;
            if (child instanceof TFolder) processFolder(child);
        }

        return groups;
    }

    /** Returns the path to graph.json inside the vault's config directory. */
    private static getGraphJsonPath(plugin: IColorfulFoldersPlugin): string {
        return `${plugin.app.vault.configDir}/graph.json`;
    }

    /** Safely reads and parses graph.json. Returns an empty object if it doesn't exist. */
    private static async readGraphJson(plugin: IColorfulFoldersPlugin): Promise<GraphJson> {
        const path = this.getGraphJsonPath(plugin);
        try {
            const exists = await plugin.app.vault.adapter.exists(path);
            if (!exists) return {};
            const raw = await plugin.app.vault.adapter.read(path);
            return JSON.parse(raw) as GraphJson;
        } catch (e) {
            console.warn('[Colorful Folders] Could not read graph.json:', e);
            return {};
        }
    }

    /** Writes the modified graph.json back to disk. */
    private static async writeGraphJson(plugin: IColorfulFoldersPlugin, data: GraphJson): Promise<void> {
        const path = this.getGraphJsonPath(plugin);
        try {
            await plugin.app.vault.adapter.write(path, JSON.stringify(data, null, 2));
        } catch (e) {
            console.error('[Colorful Folders] Could not write graph.json:', e);
        }
    }

    /**
     * Main sync entry point.
     * Builds CF groups and merges them into graph.json, preserving user-created groups.
     * Identification of CF-owned groups uses the `cf-managed-queries` tracking array
     * so no special tags need to be injected into the query strings themselves.
     */
    static async syncGraphColors(plugin: IColorfulFoldersPlugin): Promise<void> {
        if (!plugin.settings.graphColorSync) return;

        const cfGroups = this.buildColorGroups(plugin);
        const graphData = await this.readGraphJson(plugin);

        // Retrieve the set of queries we previously managed so we can remove them
        const previouslyManagedQueries = new Set<string>(graphData['cf-managed-queries'] ?? []);

        // Preserve any user-created groups (those NOT in our managed set)
        const userGroups = (graphData.colorGroups ?? []).filter(
            g => !previouslyManagedQueries.has(g.query)
        );

        // Merge: user groups first (higher priority in graph renderer), then CF groups
        graphData.colorGroups = [...userGroups, ...cfGroups];

        // Update the tracking list with only the current CF queries
        graphData['cf-managed-queries'] = cfGroups.map(g => g.query);

        await this.writeGraphJson(plugin, graphData);
    }

    /**
     * Removes all CF-generated groups from graph.json.
     * Called when the feature is disabled or the plugin unloads.
     */
    static async clearGraphColors(plugin: IColorfulFoldersPlugin): Promise<void> {
        const graphData = await this.readGraphJson(plugin);
        if (!graphData.colorGroups && !graphData['cf-managed-queries']) return;

        const managedQueries = new Set<string>(graphData['cf-managed-queries'] ?? []);
        if (managedQueries.size === 0) return;

        // Remove CF-owned groups, keep user-created groups intact
        graphData.colorGroups = (graphData.colorGroups ?? []).filter(
            g => !managedQueries.has(g.query)
        );

        // Clean up the tracking key
        delete graphData['cf-managed-queries'];

        await this.writeGraphJson(plugin, graphData);
    }
}
