import { ColorfulFoldersSettings, AutoIconData } from './types';

export const CF_FOLDER_CLOSED = encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/><path d="M2 10h20"/></svg>');
export const CF_FOLDER_OPEN = encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m6 14 1.45-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.55 6a2 2 0 0 1-1.94 1.5H4a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h3.93a2 2 0 0 1 1.66.9l.82 1.2a2 2 0 0 0 1.66.9H18a2 2 0 0 1 2 2v2"/></svg>');

export const PALETTES: Record<string, Array<{rgb: string, hex: string}>> = {
    "Vibrant Rainbow": [
        { rgb: "235, 111, 146", hex: "#eb6f92" },
        { rgb: "196, 167, 231", hex: "#c4a7e7" },
        { rgb: "246, 193, 119", hex: "#f6c177" },
        { rgb: "156, 207, 216", hex: "#9ccfd8" },
        { rgb: "49, 116, 143", hex: "#31748f" },
        { rgb: "234, 154, 151", hex: "#ea9a97" },
        { rgb: "245, 169, 127", hex: "#f5a97f" },
        { rgb: "166, 218, 149", hex: "#a6da95" },
        { rgb: "116, 199, 236", hex: "#74c7ec" },
        { rgb: "202, 158, 230", hex: "#ca9ee6" },
        { rgb: "242, 205, 205", hex: "#f2cdcd" },
        { rgb: "180, 190, 254", hex: "#b4befe" }
    ],
    "Muted Dark Mode": [
        { rgb: "186, 113, 132", hex: "#ba7184" },
        { rgb: "148, 128, 179", hex: "#9480b3" },
        { rgb: "194, 150, 91", hex: "#c2965b" },
        { rgb: "96, 148, 160", hex: "#6094a0" },
        { rgb: "48, 102, 125", hex: "#30667d" },
        { rgb: "191, 120, 117", hex: "#bf7875" },
        { rgb: "199, 138, 105", hex: "#c78a69" },
        { rgb: "128, 171, 115", hex: "#80ab73" },
        { rgb: "91, 159, 189", hex: "#5b9fbd" },
        { rgb: "160, 126, 181", hex: "#a07eb5" },
        { rgb: "186, 156, 156", hex: "#ba9c9c" },
        { rgb: "143, 151, 199", hex: "#8f97c7" }
    ],
    "Pastel Dreams": [
        { rgb: "255, 179, 186", hex: "#ffb3ba" },
        { rgb: "255, 223, 186", hex: "#ffdfba" },
        { rgb: "255, 255, 186", hex: "#ffffba" },
        { rgb: "186, 255, 201", hex: "#baffc9" },
        { rgb: "186, 225, 255", hex: "#bae1ff" },
        { rgb: "219, 186, 255", hex: "#dbbaff" },
        { rgb: "255, 186, 219", hex: "#ffbadb" },
        { rgb: "250, 218, 221", hex: "#fadadd" },
        { rgb: "207, 252, 220", hex: "#cffcdc" },
        { rgb: "204, 237, 255", hex: "#ccedff" },
        { rgb: "240, 217, 255", hex: "#f0d9ff" },
        { rgb: "255, 217, 236", hex: "#ffd9ec" }
    ],
    "Neon Cyberpunk": [
        { rgb: "255, 0, 153", hex: "#ff0099" },
        { rgb: "0, 255, 255", hex: "#00ffff" },
        { rgb: "255, 255, 0", hex: "#ffff00" },
        { rgb: "0, 255, 102", hex: "#00ff66" },
        { rgb: "153, 0, 255", hex: "#9900ff" },
        { rgb: "255, 102, 0", hex: "#ff6600" },
        { rgb: "0, 153, 255", hex: "#0099ff" },
        { rgb: "255, 0, 85", hex: "#ff0055" },
        { rgb: "51, 255, 0", hex: "#33ff00" },
        { rgb: "204, 0, 255", hex: "#cc00ff" },
        { rgb: "255, 204, 0", hex: "#ffcc00" },
        { rgb: "0, 255, 204", hex: "#00ffcc" }
    ]
};

export const DEFAULT_SETTINGS: ColorfulFoldersSettings = {
    palette: "Pastel Dreams",
    customPalette: "",
    colorMode: "cycle",
    exclusionList: "",
    outlineOnly: false,
    activeGlow: true,
    rootStyle: "translucent",
    rootOpacity: 0.548,
    subfolderOpacity: 0.201,
    tintOpacity: 0.028,
    customFolderColors: {},
    presets: {},
    glassmorphism: false,
    focusMode: false,
    autoIcons: true,
    autoIconVariety: true,
    wideAutoIcons: true,
    animateActivePath: false,
    rainbowRootText: true,
    rainbowRootBgTransparent: false,
    autoColorFiles: false,
    activeAnimationStyle: "shimmer",
    activeAnimationDuration: 4,
    showItemCounters: true,
    rootTintOpacity: 0.06,
    lightModeBrightness: 0,
    darkModeBrightness: 0,
    customIconRules: "",
    iconDebugMode: false,
    notebookNavigatorSupport: true,
    notebookNavigatorFileBackground: true,
    iconScale: 1.0,
    customIcons: {},
    cycleOffset: 0,
    showFileDivider: false,

    fileDividerText: "Files",
    dividerThickness: 1.5,
    dividerSpacing: 16,
    dividerLineStyle: "solid",
    separatorColor: "var(--text-muted)",
    dividerPillMode: true,
    dividerIconPosition: "left",
    fileBackgroundOpacity: 0.1,
    notebookNavigatorOutlineOnly: false,
    vaultPassword: "",
    isVaultLocked: false,
    showHiddenItems: false,
    showRibbonIcon: true,
};

export const AUTO_ICON_CATEGORIES: AutoIconData[] = [
    // --- Core categories ---
    { rex: /journal|daily|log|diary/i, emoji: "📅", lucide: "calendar", priority: 100, emojis: ["📅", "📆", "📝", "📔"], lucides: ["calendar", "calendar-days", "book", "pencil"] },
    { rex: /image|photo|pic|asset|gallery|album/i, emoji: "🖼️", lucide: "image", priority: 100, emojis: ["🖼️", "📷", "📸", "🎨"], lucides: ["image", "camera", "aperture", "palette"] },
    { rex: /project|task|todo|work|goal|action/i, emoji: "🚀", lucide: "rocket", priority: 100, emojis: ["🚀", "🎯", "✅", "⚡"], lucides: ["rocket", "target", "check-circle", "zap"] },
    { rex: /setting|config|pref|options|setup|tool/i, emoji: "⚙️", lucide: "settings", priority: 100 },
    { rex: /read|book|paper|article|literature|lib/i, emoji: "📚", lucide: "book-open", priority: 100 },
    { rex: /archive|old|past|backup|history|dump/i, emoji: "📦", lucide: "archive", priority: 100 },
    { rex: /idea|brain|thought|note|learn|insight|study/i, emoji: "💡", lucide: "lightbulb", priority: 100 },
    { rex: /personal|me|self|profile|account|bio/i, emoji: "👤", lucide: "user", priority: 100 },
    { rex: /finance|money|bank|pay|cost|bill|price|tax|wallet/i, emoji: "💸", lucide: "banknote", priority: 100 },
    { rex: /health|fit|exercise|diet|gym|doctor|med|sport/i, emoji: "🥗", lucide: "activity", priority: 100 },
    { rex: /travel|trip|vacation|flight|plane|map|explore/i, emoji: "✈️", lucide: "plane", priority: 100 },
    { rex: /tech|code|dev|script|bot|program|web|git|coding/i, emoji: "💻", lucide: "code", priority: 100, emojis: ["💻", "🖥️", "⌨️", "🔧"], lucides: ["code", "terminal", "cpu", "wrench"] },
    { rex: /music|audio|song|playlist|sound|record/i, emoji: "🎵", lucide: "music", priority: 100 },
    { rex: /video|movie|film|clip|youtube|stream/i, emoji: "🎬", lucide: "video", priority: 100 },
    { rex: /school|study|class|course|exam|edu|lecture|uni/i, emoji: "🎓", lucide: "graduation-cap", priority: 100 },
    { rex: /people|contact|friend|family|team|group|social/i, emoji: "👥", lucide: "users", priority: 100 },
    { rex: /inbox|new|capture|draft|start/i, emoji: "📥", lucide: "inbox", priority: 100 },
    { rex: /chat|talk|discuss|social|comm|slack|discord/i, emoji: "💬", lucide: "message-square", priority: 100 },
    { rex: /star|fav|important|prior|hot|best/i, emoji: "⭐", lucide: "star", priority: 100 },
    { rex: /lock|secret|private|secure|vault|pass/i, emoji: "🔒", lucide: "lock", priority: 100 },
    { rex: /home|house|ref|base|living/i, emoji: "🏠", lucide: "home", priority: 100 },
    { rex: /search|find|query|explore/i, emoji: "🔍", lucide: "search", priority: 100 },
    { rex: /mail|letter|message|email/i, emoji: "📧", lucide: "mail", priority: 100 },
    { rex: /write|pen|edit|create|author/i, emoji: "🖋️", lucide: "pen-tool", priority: 100 },

    // --- Expanded categories ---
    { rex: /design|ui|ux|figma|sketch|mockup/i, emoji: "✨", lucide: "layout", priority: 90 },
    { rex: /data|csv|excel|sheet|table|stats|analytics/i, emoji: "📊", lucide: "bar-chart-2", priority: 90 },
    { rex: /presentation|slides|ppt|deck/i, emoji: "📽️", lucide: "presentation", priority: 90 },
    { rex: /document|doc|word|report|text/i, emoji: "📄", lucide: "file-text", priority: 90 },
    { rex: /pdf|ebook/i, emoji: "📕", lucide: "file", priority: 90 },
    { rex: /zip|rar|compressed|archive/i, emoji: "🗜️", lucide: "package", priority: 90 },
    { rex: /cloud|sync|drive|storage/i, emoji: "☁️", lucide: "cloud", priority: 90 },
    { rex: /shopping|cart|store|shop|buy|order/i, emoji: "🛒", lucide: "shopping-cart", priority: 90 },
    { rex: /food|recipe|meal|drink|cook|restaurant/i, emoji: "🍔", lucide: "utensils", priority: 90 },
    { rex: /nature|tree|plant|eco|environment/i, emoji: "🌱", lucide: "leaf", priority: 90 },
    { rex: /game|play|fun|console|steam/i, emoji: "🎮", lucide: "gamepad-2", priority: 90 },
    { rex: /news|update|press|media|headline/i, emoji: "📰", lucide: "newspaper", priority: 90 },
    { rex: /calendar|event|schedule|date|time/i, emoji: "📆", lucide: "calendar-days", priority: 90 },
    { rex: /map|location|gps|place|address/i, emoji: "📍", lucide: "map-pin", priority: 90 },
    { rex: /alert|warn|error|bug|issue/i, emoji: "⚠️", lucide: "alert-triangle", priority: 90 },
    { rex: /science|lab|experiment|chemistry|biology/i, emoji: "🔬", lucide: "flask-conical", priority: 90 },
    { rex: /career|job|resume|cv|work/i, emoji: "💼", lucide: "briefcase", priority: 90 },
    { rex: /server|database|infra|network/i, emoji: "🖧", lucide: "server", priority: 90 },
    { rex: /ai|ml|neural|model/i, emoji: "🤖", lucide: "cpu", priority: 90 },

    // --- More diverse icons ---
    { rex: /photo-edit|design|art|draw|paint/i, emoji: "🎨", lucide: "brush", priority: 80 },
    { rex: /travel-doc|passport|visa/i, emoji: "🪪", lucide: "id-card", priority: 80 },
    { rex: /question|help|support|faq|ask/i, emoji: "❓", lucide: "help-circle", priority: 85, emojis: ["❓", "❔", "🤔"], lucides: ["help-circle", "message-square-question", "badge-help"] },
    { rex: /quote|cite|ref|mention|block/i, emoji: "💬", lucide: "quote", priority: 85, lucides: ["quote", "text-quote"] },
    { rex: /template|boiler|preset|layout|blueprint/i, emoji: "📝", lucide: "layout-template", priority: 85, emojis: ["📝", "📋", "📐"], lucides: ["layout-template", "copy", "ruler"] },
    { rex: /tv|series|episode|show|drama|media/i, emoji: "📺", lucide: "tv", priority: 85, emojis: ["📺", "🎬", "🎭"], lucides: ["tv", "monitor-play", "clapperboard"] },
    { rex: /visual|view|display|watch|look|eye|see/i, emoji: "👁️", lucide: "eye", priority: 85, emojis: ["👁️", "👓", "🔭"], lucides: ["eye", "glasses", "telescope"] },
    { rex: /recent|update|history|mod|time|new/i, emoji: "🕒", lucide: "history", priority: 85, emojis: ["🕒", "🕙", "⏳", "📅"], lucides: ["history", "clock", "calendar-clock", "sparkles"] },
    { rex: /source|origin|root|base|data|lib|bib/i, emoji: "📁", lucide: "database", priority: 85, emojis: ["📁", "📥", "📊"], lucides: ["database", "library", "binary"] },
    { rex: /thing|object|stuff|entity|misc|item/i, emoji: "📦", lucide: "package", priority: 80, emojis: ["📦", "🎁", "🗳️"], lucides: ["package", "layers", "box"] },
    { rex: /review|crit|feedback|eval/i, emoji: "🔎", lucide: "search", priority: 85, lucides: ["search", "check-square", "clipboard-check"] },
    { rex: /draft|wip|process|build/i, emoji: "🚧", lucide: "wrench", priority: 85, emojis: ["🚧", "🛠️", "🏗️"], lucides: ["wrench", "construction", "hammer"] },
    { rex: /security|auth|key|password/i, emoji: "🔑", lucide: "key", priority: 80 },
    { rex: /download|install|setup/i, emoji: "⬇️", lucide: "download", priority: 80 },
    { rex: /upload|share|publish/i, emoji: "⬆️", lucide: "upload", priority: 80 },
    { rex: /trash|delete|remove|bin/i, emoji: "🗑️", lucide: "trash", priority: 80 },
    { rex: /energy|power|electric|battery/i, emoji: "🔋", lucide: "battery-charging", priority: 80 },
    { rex: /weather|climate|forecast|rain|sun/i, emoji: "⛅", lucide: "cloud-sun", priority: 80 },
    { rex: /holiday|celebration|party|festival/i, emoji: "🎉", lucide: "gift", priority: 80 },
    { rex: /transport|car|bike|bus|train/i, emoji: "🚗", lucide: "car", priority: 80 },
    { rex: /construction|tools|fix|repair/i, emoji: "🛠️", lucide: "wrench", priority: 80 },
    { rex: /photo-camera|shoot|capture/i, emoji: "📷", lucide: "camera", priority: 80 },
    { rex: /clipboard|notes|tasks|checklist/i, emoji: "📋", lucide: "clipboard-list", priority: 80 },
    { rex: /downloaded|software|apps|exe|pkg/i, emoji: "📦", lucide: "box", priority: 80 },
    { rex: /currency|crypto|bitcoin|ethereum/i, emoji: "🪙", lucide: "coins", priority: 80 },
];
